import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/next";
import { Fredoka } from "next/font/google";
import Script from "next/script"; // <--- 1. IMPORTAR ESTO
import "./globals.css";

const fredoka = Fredoka({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-fredoka",
});

export const metadata: Metadata = {
  title: "Cuento Kilómetros",
  description: "Generated by create next app",
  icons: {
    icon: "/images/ui/renault-logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fredoka.variable} font-sans antialiased`}>
        
        {/* --- GOOGLE ANALYTICS START --- */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-YKNCRVP26Y"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'G-YKNCRVP26Y');
          `}
        </Script>
        {/* --- GOOGLE ANALYTICS END --- */}

        {children}
        <Analytics />
      </body>
    </html>
  );
}